### ISSUE TITLE
JSON model format incompatible with escher

### ISSUE THREAD

**Issue by HettieC** [LCSB-BioCore/COBREXA.jl#758] opened 2023-02-17 12:59 UTC
In the #next branch:
Using ```convert(JSONModel, model)```  produces a json file with the first line ```{
    "json": {
        "metabolites": [```, but escher doesn't recognise this format, it works if you get ride of the  ```{"json":```, so that the first line is instead ```{ "metabolites": [```.

**Comment by exaexa** [comment] 2023-02-17 13:30
I just tested with SBML->JSON and matlab->JSON on current `next` and can't reproduce; any repro script welcome

**Comment by HettieC** [comment] 2023-02-21 12:40
Hi! Sorry for slow response! This is in the ```next``` branch, and this is the script to reproduce: 
```
using COBREXA.Everything, JSON

model = ObjectModel(id = "example")

mets = [Metabolite(string("m",num)) for num = 1:2]
add_metabolites!(model,mets)
rxn = Reaction("r1", Dict("m1" => -1, "m2"=>1))
add_reaction!(model,rxn)

open("example_model.json","w") do io 
    JSON.print(io,convert(JSONModel, model))
end
```

and it produces the file ```example_model.json``` which starts with ```{
    "json": {
        "metabolites": [
            { ``` and does not show up as a model when used in escher. Possibly it's a problem with the ```JSON``` package and not with cobrexa. 
Is there a built in function to save models that I'm missing?

**Comment by exaexa** [comment] 2023-02-21 13:17
ah yes, you're serializing the whole JSON model structure even with the COBREXA wrapper, which produces the "json" part. JSON package is too smart here and actually handles this without an error, despite it technically should be one.

You should be able to use
```julia
save_model(model, "example_model.json")
```
...to do this directly.

Alternatively, you can fix your example by extracting the JSON part of the model as follows:
```julia
    JSON.print(io,convert(JSONModel, model).json)
```

**Comment by HettieC** [comment] 2023-02-21 13:56
OK great, thanks!

**Comment by exaexa** [comment] 2023-02-21 15:06
Did that fix it? (I'd close the issue)

**Comment by HettieC** [comment] 2023-02-21 15:41
Yeah it does :)

**Closed** 2023-02-22 08:28 UTC
